### ISSUE TITLE
[EPIC] [KEv2] Kinetic Engine v2.0

### ISSUE THREAD

**Issue by ahm23** [ahm23/Orbital-Simulator#4]
- [x] #11 
- [x] #10 
- [x] #9 
- [ ] ~~#15~~  -- PUSHED TO DEV DESPITE LACK OF TESTING. KEv2 REQUIRED FOR PIPELINE DEVELOPMENT.

**Comment by 1112zakaria** [comment]
Okay, now THIS is epic.
